rootProject.name = "projectcheckins"
include("annotations")
include("code-coverage-report")
include("core")
include("bootstrap")
include("http")
include("email")
include("email-http")
include("multitenancy")
include("netty")
include("security")
include("security-http")
include("processor")
include("repository-eclipsestore")
